[package]
name = "bake-kas"
version = "0.1.0"
edition = "2021"
rust-version = "1.66.0"

[dependencies]
pyo3 = { version = "0.19.2", features = ["auto-initialize"] }
serde = "1.0.188"
serde_json = "1.0.107"
serde_yaml = "0.9.25"
valico = "4.0.0"
