[package]
name = "core-vcs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["process"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

